// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ArtifactRegistryStub {
    func listDockerImages(
      request: ListDockerImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListDockerImagesResponse

    func getDockerImage(
      request: GetDockerImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.DockerImage

    func listMavenArtifacts(
      request: ListMavenArtifactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListMavenArtifactsResponse

    func getMavenArtifact(
      request: GetMavenArtifactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.MavenArtifact

    func listNpmPackages(
      request: ListNpmPackagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListNpmPackagesResponse

    func getNpmPackage(
      request: GetNpmPackageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.NpmPackage

    func listPythonPackages(
      request: ListPythonPackagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListPythonPackagesResponse

    func getPythonPackage(
      request: GetPythonPackageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.PythonPackage

    func importAptArtifacts(
      request: ImportAptArtifactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importYumArtifacts(
      request: ImportYumArtifactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRepositories(
      request: ListRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListRepositoriesResponse

    func getRepository(
      request: GetRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Repository

    func createRepository(
      request: CreateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Repository

    func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPackages(
      request: ListPackagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListPackagesResponse

    func getPackage(
      request: GetPackageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Package

    func deletePackage(
      request: DeletePackageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listVersions(
      request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListVersionsResponse

    func getVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Version

    func deleteVersion(
      request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func batchDeleteVersions(
      request: BatchDeleteVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateVersion(
      request: UpdateVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Version

    func listFiles(
      request: ListFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListFilesResponse

    func getFile(
      request: GetFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.File

    func deleteFile(
      request: DeleteFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateFile(
      request: UpdateFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.File

    func listTags(
      request: ListTagsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListTagsResponse

    func getTag(
      request: GetTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag

    func createTag(
      request: CreateTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag

    func updateTag(
      request: UpdateTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag

    func deleteTag(
      request: DeleteTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createRule(
      request: CreateRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule

    func listRules(
      request: ListRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListRulesResponse

    func getRule(
      request: GetRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule

    func updateRule(
      request: UpdateRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule

    func deleteRule(
      request: DeleteRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func getProjectSettings(
      request: GetProjectSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ProjectSettings

    func updateProjectSettings(
      request: UpdateProjectSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ProjectSettings

    func getVpcscconfig(
      request: GetVPCSCConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.VPCSCConfig

    func updateVpcscconfig(
      request: UpdateVPCSCConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.VPCSCConfig

    func updatePackage(
      request: UpdatePackageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Package

    func listAttachments(
      request: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListAttachmentsResponse

    func getAttachment(
      request: GetAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Attachment

    func createAttachment(
      request: CreateAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAttachment(
      request: DeleteAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportArtifact(
      request: ExportArtifactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
