// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ArtifactRegistryLogging: ArtifactRegistryStub {
    let inner: any ArtifactRegistryStub
    let logger: Logger

    public init(_ inner: any ArtifactRegistryStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-devtools-artifactregistry-v1"
      logger[metadataKey: "gcp.client.service"] = "artifactregistry"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ArtifactRegistry"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listDockerImages(
      request: ListDockerImagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListDockerImagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDockerImages",
        action: {
          (r: ListDockerImagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListDockerImagesResponse
          in
          return try await self.inner.listDockerImages(request: r, options: o)
        })
    }

    public func getDockerImage(
      request: GetDockerImageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.DockerImage {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDockerImage",
        action: {
          (r: GetDockerImageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.DockerImage
          in
          return try await self.inner.getDockerImage(request: r, options: o)
        })
    }

    public func listMavenArtifacts(
      request: ListMavenArtifactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListMavenArtifactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMavenArtifacts",
        action: {
          (r: ListMavenArtifactsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListMavenArtifactsResponse
          in
          return try await self.inner.listMavenArtifacts(request: r, options: o)
        })
    }

    public func getMavenArtifact(
      request: GetMavenArtifactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.MavenArtifact {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMavenArtifact",
        action: {
          (r: GetMavenArtifactRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.MavenArtifact
          in
          return try await self.inner.getMavenArtifact(request: r, options: o)
        })
    }

    public func listNpmPackages(
      request: ListNpmPackagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListNpmPackagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNpmPackages",
        action: {
          (r: ListNpmPackagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListNpmPackagesResponse
          in
          return try await self.inner.listNpmPackages(request: r, options: o)
        })
    }

    public func getNpmPackage(
      request: GetNpmPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.NpmPackage {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNpmPackage",
        action: {
          (r: GetNpmPackageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.NpmPackage
          in
          return try await self.inner.getNpmPackage(request: r, options: o)
        })
    }

    public func listPythonPackages(
      request: ListPythonPackagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListPythonPackagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPythonPackages",
        action: {
          (r: ListPythonPackagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListPythonPackagesResponse
          in
          return try await self.inner.listPythonPackages(request: r, options: o)
        })
    }

    public func getPythonPackage(
      request: GetPythonPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.PythonPackage {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPythonPackage",
        action: {
          (r: GetPythonPackageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.PythonPackage
          in
          return try await self.inner.getPythonPackage(request: r, options: o)
        })
    }

    public func importAptArtifacts(
      request: ImportAptArtifactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importAptArtifacts",
        action: {
          (r: ImportAptArtifactsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importAptArtifacts(request: r, options: o)
        })
    }

    public func importYumArtifacts(
      request: ImportYumArtifactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importYumArtifacts",
        action: {
          (r: ImportYumArtifactsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importYumArtifacts(request: r, options: o)
        })
    }

    public func listRepositories(
      request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListRepositoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRepositories",
        action: {
          (r: ListRepositoriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListRepositoriesResponse
          in
          return try await self.inner.listRepositories(request: r, options: o)
        })
    }

    public func getRepository(
      request: GetRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Repository {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRepository",
        action: {
          (r: GetRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Repository
          in
          return try await self.inner.getRepository(request: r, options: o)
        })
    }

    public func createRepository(
      request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRepository",
        action: {
          (r: CreateRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRepository(request: r, options: o)
        })
    }

    public func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Repository {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRepository",
        action: {
          (r: UpdateRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Repository
          in
          return try await self.inner.updateRepository(request: r, options: o)
        })
    }

    public func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRepository",
        action: {
          (r: DeleteRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRepository(request: r, options: o)
        })
    }

    public func listPackages(
      request: ListPackagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListPackagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPackages",
        action: {
          (r: ListPackagesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListPackagesResponse
          in
          return try await self.inner.listPackages(request: r, options: o)
        })
    }

    public func getPackage(
      request: GetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Package {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPackage",
        action: {
          (r: GetPackageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Package
          in
          return try await self.inner.getPackage(request: r, options: o)
        })
    }

    public func deletePackage(
      request: DeletePackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePackage",
        action: {
          (r: DeletePackageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePackage(request: r, options: o)
        })
    }

    public func listVersions(
      request: ListVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVersions",
        action: {
          (r: ListVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListVersionsResponse
          in
          return try await self.inner.listVersions(request: r, options: o)
        })
    }

    public func getVersion(
      request: GetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Version {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVersion",
        action: {
          (r: GetVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Version
          in
          return try await self.inner.getVersion(request: r, options: o)
        })
    }

    public func deleteVersion(
      request: DeleteVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteVersion",
        action: {
          (r: DeleteVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteVersion(request: r, options: o)
        })
    }

    public func batchDeleteVersions(
      request: BatchDeleteVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchDeleteVersions",
        action: {
          (r: BatchDeleteVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchDeleteVersions(request: r, options: o)
        })
    }

    public func updateVersion(
      request: UpdateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Version {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateVersion",
        action: {
          (r: UpdateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Version
          in
          return try await self.inner.updateVersion(request: r, options: o)
        })
    }

    public func listFiles(
      request: ListFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListFilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFiles",
        action: {
          (r: ListFilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListFilesResponse
          in
          return try await self.inner.listFiles(request: r, options: o)
        })
    }

    public func getFile(
      request: GetFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.File {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFile",
        action: {
          (r: GetFileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.File
          in
          return try await self.inner.getFile(request: r, options: o)
        })
    }

    public func deleteFile(
      request: DeleteFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteFile",
        action: {
          (r: DeleteFileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteFile(request: r, options: o)
        })
    }

    public func updateFile(
      request: UpdateFileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.File {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFile",
        action: {
          (r: UpdateFileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.File
          in
          return try await self.inner.updateFile(request: r, options: o)
        })
    }

    public func listTags(
      request: ListTagsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListTagsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTags",
        action: {
          (r: ListTagsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListTagsResponse
          in
          return try await self.inner.listTags(request: r, options: o)
        })
    }

    public func getTag(
      request: GetTagRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTag",
        action: {
          (r: GetTagRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Tag
          in
          return try await self.inner.getTag(request: r, options: o)
        })
    }

    public func createTag(
      request: CreateTagRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTag",
        action: {
          (r: CreateTagRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Tag
          in
          return try await self.inner.createTag(request: r, options: o)
        })
    }

    public func updateTag(
      request: UpdateTagRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Tag {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTag",
        action: {
          (r: UpdateTagRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Tag
          in
          return try await self.inner.updateTag(request: r, options: o)
        })
    }

    public func deleteTag(
      request: DeleteTagRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTag",
        action: { (r: DeleteTagRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTag(request: r, options: o)
        })
    }

    public func createRule(
      request: CreateRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRule",
        action: {
          (r: CreateRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Rule
          in
          return try await self.inner.createRule(request: r, options: o)
        })
    }

    public func listRules(
      request: ListRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRules",
        action: {
          (r: ListRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListRulesResponse
          in
          return try await self.inner.listRules(request: r, options: o)
        })
    }

    public func getRule(
      request: GetRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRule",
        action: {
          (r: GetRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Rule
          in
          return try await self.inner.getRule(request: r, options: o)
        })
    }

    public func updateRule(
      request: UpdateRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Rule {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRule",
        action: {
          (r: UpdateRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Rule
          in
          return try await self.inner.updateRule(request: r, options: o)
        })
    }

    public func deleteRule(
      request: DeleteRuleRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRule",
        action: { (r: DeleteRuleRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteRule(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getProjectSettings(
      request: GetProjectSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ProjectSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProjectSettings",
        action: {
          (r: GetProjectSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ProjectSettings
          in
          return try await self.inner.getProjectSettings(request: r, options: o)
        })
    }

    public func updateProjectSettings(
      request: UpdateProjectSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ProjectSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateProjectSettings",
        action: {
          (r: UpdateProjectSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ProjectSettings
          in
          return try await self.inner.updateProjectSettings(request: r, options: o)
        })
    }

    public func getVpcscconfig(
      request: GetVPCSCConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.VPCSCConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVpcscconfig",
        action: {
          (r: GetVPCSCConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.VPCSCConfig
          in
          return try await self.inner.getVpcscconfig(request: r, options: o)
        })
    }

    public func updateVpcscconfig(
      request: UpdateVPCSCConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.VPCSCConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateVpcscconfig",
        action: {
          (r: UpdateVPCSCConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.VPCSCConfig
          in
          return try await self.inner.updateVpcscconfig(request: r, options: o)
        })
    }

    public func updatePackage(
      request: UpdatePackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Package {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePackage",
        action: {
          (r: UpdatePackageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Package
          in
          return try await self.inner.updatePackage(request: r, options: o)
        })
    }

    public func listAttachments(
      request: ListAttachmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.ListAttachmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAttachments",
        action: {
          (r: ListAttachmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.ListAttachmentsResponse
          in
          return try await self.inner.listAttachments(request: r, options: o)
        })
    }

    public func getAttachment(
      request: GetAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudArtifactRegistryV1.Attachment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAttachment",
        action: {
          (r: GetAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudArtifactRegistryV1.Attachment
          in
          return try await self.inner.getAttachment(request: r, options: o)
        })
    }

    public func createAttachment(
      request: CreateAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAttachment",
        action: {
          (r: CreateAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAttachment(request: r, options: o)
        })
    }

    public func deleteAttachment(
      request: DeleteAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAttachment",
        action: {
          (r: DeleteAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAttachment(request: r, options: o)
        })
    }

    public func exportArtifact(
      request: ExportArtifactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportArtifact",
        action: {
          (r: ExportArtifactRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportArtifact(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
