// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Artifact policy configuration for repository cleanup policies.
public struct CleanupPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The user-provided ID of the cleanup policy.
  public var id: Swift.String = Swift.String()

  /// Policy action.
  public var action: CleanupPolicy.Action = CleanupPolicy.Action()

  public var conditionType: OneOf_ConditionType? = nil

  /// Initialize a new instance of `CleanupPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CleanupPolicy().with { $0.condition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case condition = "condition"
    case mostRecentVersions = "mostRecentVersions"
    case id = "id"
    case action = "action"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.action = try container.decode(CleanupPolicy.Action.self, forKey: .action)

    var conditionType: OneOf_ConditionType? = nil
    let conditionTypeCheckAndSet = {
      if conditionType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'conditionType'"))
      }
      conditionType = $0
    }
    if let condition = try container.decodeIfPresent(
      CleanupPolicyCondition?.self, forKey: .condition)
    {
      try conditionTypeCheckAndSet(.condition(condition))
    }
    if let mostRecentVersions = try container.decodeIfPresent(
      CleanupPolicyMostRecentVersions?.self, forKey: .mostRecentVersions)
    {
      try conditionTypeCheckAndSet(.mostRecentVersions(mostRecentVersions))
    }
    self.conditionType = conditionType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.action, forKey: .action)

    if let choice = self.conditionType {
      switch choice {
      case .condition(let value):
        try container.encode(value, forKey: .condition)
      case .mostRecentVersions(let value):
        try container.encode(value, forKey: .mostRecentVersions)
      }
    }
  }

  /// Action type for a cleanup policy.
  public enum Action: Codable, Equatable, Sendable {
    /// Action not specified.
    case unspecified
    /// Delete action.
    case delete
    /// Keep action.
    case keep
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .delete: return 1
      case .keep: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .delete: return "DELETE"
      case .keep: return "KEEP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Action/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "DELETE": self = .delete
      case "KEEP": self = .keep
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Action/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .delete
      case 2: self = .keep
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .delete: return try container.encode(1)
      case .keep: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_ConditionType: Codable, Equatable, Sendable {
    /// Policy condition for matching versions.
    indirect case condition(CleanupPolicyCondition?)
    /// Policy condition for retaining a minimum number of versions. May only be
    /// specified with a Keep action.
    indirect case mostRecentVersions(CleanupPolicyMostRecentVersions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.CleanupPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
