// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CleanupPolicyCondition is a set of conditions attached to a CleanupPolicy.
/// If multiple entries are set, all must be satisfied for the condition to be
/// satisfied.
public struct CleanupPolicyCondition: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Match versions by tag status.
  public var tagState: CleanupPolicyCondition.TagState? = nil

  /// Match versions by tag prefix. Applied on any prefix match.
  public var tagPrefixes: [Swift.String] = []

  /// Match versions by version name prefix. Applied on any prefix match.
  public var versionNamePrefixes: [Swift.String] = []

  /// Match versions by package prefix. Applied on any prefix match.
  public var packageNamePrefixes: [Swift.String] = []

  /// Match versions older than a duration.
  public var olderThan: GoogleCloudWKT.Duration? = nil

  /// Match versions newer than a duration.
  public var newerThan: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `CleanupPolicyCondition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CleanupPolicyCondition().with { $0.tagState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Statuses applying to versions.
  public enum TagState: Codable, Equatable, Sendable {
    /// Tag status not specified.
    case unspecified
    /// Applies to tagged versions only.
    case tagged
    /// Applies to untagged versions only.
    case untagged
    /// Applies to all versions.
    case any
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .tagged: return 1
      case .untagged: return 2
      case .any: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TAG_STATE_UNSPECIFIED"
      case .tagged: return "TAGGED"
      case .untagged: return "UNTAGGED"
      case .any: return "ANY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TagState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TAG_STATE_UNSPECIFIED": self = .unspecified
      case "TAGGED": self = .tagged
      case "UNTAGGED": self = .untagged
      case "ANY": self = .any
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TagState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .tagged
      case 2: self = .untagged
      case 3: self = .any
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .tagged: return try container.encode(1)
      case .untagged: return try container.encode(2)
      case .any: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.CleanupPolicyCondition"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
