// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// DockerImage represents a docker artifact.
/// The following fields are returned as untyped metadata in the Version
/// resource, using camelcase keys (i.e. metadata.imageSizeBytes):
/// * imageSizeBytes
/// * mediaType
/// * buildTime
public struct DockerImage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. registry_location, project_id, repository_name and image id forms
  /// a unique image
  /// name:`projects/<project_id>/locations/<location>/repositories/<repository_name>/dockerImages/<docker_image>`.
  /// For example,
  /// "projects/test-project/locations/us-west4/repositories/test-repo/dockerImages/
  /// nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf",
  /// where "us-west4" is the registry_location, "test-project" is the
  /// project_id, "test-repo" is the repository_name and
  /// "nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf"
  /// is the image's digest.
  public var name: Swift.String = Swift.String()

  /// Required. URL to access the image.
  /// Example:
  /// us-west4-docker.pkg.dev/test-project/test-repo/nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf
  public var uri: Swift.String = Swift.String()

  /// Tags attached to this image.
  public var tags: [Swift.String] = []

  /// Calculated size of the image.
  /// This field is returned as the 'metadata.imageSizeBytes' field in the
  /// Version resource.
  public var imageSizeBytes: Swift.Int64 = Swift.Int64()

  /// Time the image was uploaded.
  public var uploadTime: GoogleCloudWKT.Timestamp? = nil

  /// Media type of this image, e.g.
  /// "application/vnd.docker.distribution.manifest.v2+json".
  /// This field is returned as the 'metadata.mediaType' field in the
  /// Version resource.
  public var mediaType: Swift.String = Swift.String()

  /// The time this image was built.
  /// This field is returned as the 'metadata.buildTime' field in the
  /// Version resource.
  /// The build time is returned to the client as an RFC 3339 string, which can
  /// be easily used with the JavaScript Date constructor.
  public var buildTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the docker image was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// ArtifactType of this image, e.g. "application/vnd.example+type".
  /// If the `subject_digest` is set and no `artifact_type` is given, the
  /// `media_type` will be considered as the `artifact_type`. This field is
  /// returned as the `metadata.artifactType` field in the Version resource.
  public var artifactType: Swift.String = Swift.String()

  /// Optional. For multi-arch images (manifest lists), this field contains the
  /// list of image manifests.
  public var imageManifests: [ImageManifest] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DockerImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DockerImage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uri = CodingKeys(stringValue: "uri")
    static let tags = CodingKeys(stringValue: "tags")
    static let imageSizeBytes = CodingKeys(stringValue: "imageSizeBytes")
    static let uploadTime = CodingKeys(stringValue: "uploadTime")
    static let mediaType = CodingKeys(stringValue: "mediaType")
    static let buildTime = CodingKeys(stringValue: "buildTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let artifactType = CodingKeys(stringValue: "artifactType")
    static let imageManifests = CodingKeys(stringValue: "imageManifests")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uri",
      "tags",
      "imageSizeBytes",
      "uploadTime",
      "mediaType",
      "buildTime",
      "updateTime",
      "artifactType",
      "imageManifests",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .imageSizeBytes) {
      self.imageSizeBytes = value
    }
    self.uploadTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .uploadTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mediaType) {
      self.mediaType = value
    }
    self.buildTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .buildTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .artifactType) {
      self.artifactType = value
    }
    if let value = try container.decodeIfPresent([ImageManifest].self, forKey: .imageManifests) {
      self.imageManifests = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.imageSizeBytes, forKey: .imageSizeBytes)
    try container.encodeIfPresent(self.uploadTime, forKey: .uploadTime)
    try container.encode(self.mediaType, forKey: .mediaType)
    try container.encodeIfPresent(self.buildTime, forKey: .buildTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.artifactType, forKey: .artifactType)
    try container.encode(self.imageManifests, forKey: .imageManifests)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.DockerImage"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
