// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DockerImage represents a docker artifact.
/// The following fields are returned as untyped metadata in the Version
/// resource, using camelcase keys (i.e. metadata.imageSizeBytes):
/// * imageSizeBytes
/// * mediaType
/// * buildTime
public struct DockerImage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. registry_location, project_id, repository_name and image id forms
  /// a unique image
  /// name:`projects/<project_id>/locations/<location>/repositories/<repository_name>/dockerImages/<docker_image>`.
  /// For example,
  /// "projects/test-project/locations/us-west4/repositories/test-repo/dockerImages/
  /// nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf",
  /// where "us-west4" is the registry_location, "test-project" is the
  /// project_id, "test-repo" is the repository_name and
  /// "nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf"
  /// is the image's digest.
  public var name: Swift.String = Swift.String()

  /// Required. URL to access the image.
  /// Example:
  /// us-west4-docker.pkg.dev/test-project/test-repo/nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf
  public var uri: Swift.String = Swift.String()

  /// Tags attached to this image.
  public var tags: [Swift.String] = []

  /// Calculated size of the image.
  /// This field is returned as the 'metadata.imageSizeBytes' field in the
  /// Version resource.
  public var imageSizeBytes: Swift.Int64 = Swift.Int64()

  /// Time the image was uploaded.
  public var uploadTime: GoogleCloudWkt.Timestamp? = nil

  /// Media type of this image, e.g.
  /// "application/vnd.docker.distribution.manifest.v2+json".
  /// This field is returned as the 'metadata.mediaType' field in the
  /// Version resource.
  public var mediaType: Swift.String = Swift.String()

  /// The time this image was built.
  /// This field is returned as the 'metadata.buildTime' field in the
  /// Version resource.
  /// The build time is returned to the client as an RFC 3339 string, which can
  /// be easily used with the JavaScript Date constructor.
  public var buildTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the docker image was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// ArtifactType of this image, e.g. "application/vnd.example+type".
  /// If the `subject_digest` is set and no `artifact_type` is given, the
  /// `media_type` will be considered as the `artifact_type`. This field is
  /// returned as the `metadata.artifactType` field in the Version resource.
  public var artifactType: Swift.String = Swift.String()

  /// Optional. For multi-arch images (manifest lists), this field contains the
  /// list of image manifests.
  public var imageManifests: [ImageManifest] = []

  /// Initialize a new instance of `DockerImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DockerImage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.DockerImage"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
