// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The LRO metadata for exporting an artifact.
public struct ExportArtifactMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The exported artifact files.
  public var exportedFiles: [ExportArtifactMetadata.ExportedFile] = []

  /// Initialize a new instance of `ExportArtifactMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportArtifactMetadata().with { $0.exportedFiles = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The exported artifact file.
  public struct ExportedFile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of the exported artifact file.
    /// Format: `projects/p1/locations/us/repositories/repo1/files/file1`
    public var name: Swift.String = Swift.String()

    /// The hashes of the file content.
    public var hashes: [Hash] = []

    /// The destination the file was exported to.
    public var destination: OneOf_Destination? = nil

    /// Initialize a new instance of `ExportedFile`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportedFile().with { $0.gcsObjectPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gcsObjectPath = "gcsObjectPath"
      case name = "name"
      case hashes = "hashes"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.name = try container.decode(Swift.String.self, forKey: .name)
      self.hashes = try container.decode([Hash].self, forKey: .hashes)

      var destination: OneOf_Destination? = nil
      let destinationCheckAndSet = {
        if destination != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'destination'"))
        }
        destination = $0
      }
      if let gcsObjectPath = try container.decodeIfPresent(
        Swift.String.self, forKey: .gcsObjectPath)
      {
        try destinationCheckAndSet(.gcsObjectPath(gcsObjectPath))
      }
      self.destination = destination
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.hashes, forKey: .hashes)

      if let choice = self.destination {
        switch choice {
        case .gcsObjectPath(let value):
          try container.encode(value, forKey: .gcsObjectPath)
        }
      }
    }

    /// The destination the file was exported to.
    public enum OneOf_Destination: Codable, Equatable, Sendable {
      /// Cloud Storage Object path of the exported file. Examples:
      /// `dst_bucket/file1`, `dst_bucket/sub_dir/file1`
      case gcsObjectPath(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.devtools.artifactregistry.v1.ExportArtifactMetadata.ExportedFile"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ExportArtifactMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
