// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The LRO metadata for exporting an artifact.
public struct ExportArtifactMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The exported artifact files.
  public var exportedFiles: [ExportArtifactMetadata.ExportedFile] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExportArtifactMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportArtifactMetadata().with { $0.exportedFiles = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let exportedFiles = CodingKeys(stringValue: "exportedFiles")

    static let _knownKeys: Set<Swift.String> = [
      "exportedFiles"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ExportArtifactMetadata.ExportedFile].self, forKey: .exportedFiles)
    {
      self.exportedFiles = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.exportedFiles, forKey: .exportedFiles)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The exported artifact file.
  public struct ExportedFile: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of the exported artifact file.
    /// Format: `projects/p1/locations/us/repositories/repo1/files/file1`
    public var name: Swift.String = Swift.String()

    /// The hashes of the file content.
    public var hashes: [Hash] = []

    /// The destination the file was exported to.
    public var destination: OneOf_Destination? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExportedFile`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportedFile().with { $0.gcsObjectPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gcsObjectPath = CodingKeys(stringValue: "gcsObjectPath")
      static let name = CodingKeys(stringValue: "name")
      static let hashes = CodingKeys(stringValue: "hashes")

      static let _knownKeys: Set<Swift.String> = [
        "gcsObjectPath",
        "name",
        "hashes",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent([Hash].self, forKey: .hashes) {
        self.hashes = value
      }

      var destination: OneOf_Destination? = nil
      let destinationCheckAndSet = {
        if destination != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'destination'"))
        }
        destination = $0
      }
      if let gcsObjectPath = try container.decodeIfPresent(
        Swift.String.self, forKey: .gcsObjectPath)
      {
        try destinationCheckAndSet(.gcsObjectPath(gcsObjectPath))
      }
      self.destination = destination
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.hashes, forKey: .hashes)

      if let choice = self.destination {
        switch choice {
        case .gcsObjectPath(let value):
          try container.encode(value, forKey: .gcsObjectPath)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The destination the file was exported to.
    public enum OneOf_Destination: Codable, Equatable, Sendable {
      /// Cloud Storage Object path of the exported file. Examples:
      /// `dst_bucket/file1`, `dst_bucket/sub_dir/file1`
      case gcsObjectPath(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.devtools.artifactregistry.v1.ExportArtifactMetadata.ExportedFile"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ExportArtifactMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
