// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Files store content that is potentially associated with Packages or Versions.
public struct File: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the file, for example:
  /// `projects/p1/locations/us-central1/repositories/repo1/files/a%2Fb%2Fc.txt`.
  /// If the file ID part contains slashes, they are escaped.
  public var name: Swift.String = Swift.String()

  /// The size of the File in bytes.
  public var sizeBytes: Swift.Int64 = Swift.Int64()

  /// The hashes of the file content.
  public var hashes: [Hash] = []

  /// Output only. The time when the File was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the File was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// The name of the Package or Version that owns this file, if any.
  public var owner: Swift.String = Swift.String()

  /// Output only. The time when the last attempt to refresh the file's data was
  /// made. Only set when the repository is remote.
  public var fetchTime: GoogleWKT.Timestamp? = nil

  /// Optional. Client specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `File`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = File().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let sizeBytes = CodingKeys(stringValue: "sizeBytes")
    static let hashes = CodingKeys(stringValue: "hashes")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let owner = CodingKeys(stringValue: "owner")
    static let fetchTime = CodingKeys(stringValue: "fetchTime")
    static let annotations = CodingKeys(stringValue: "annotations")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "sizeBytes",
      "hashes",
      "createTime",
      "updateTime",
      "owner",
      "fetchTime",
      "annotations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sizeBytes) {
      self.sizeBytes = value
    }
    if let value = try container.decodeIfPresent([Hash].self, forKey: .hashes) {
      self.hashes = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .owner) {
      self.owner = value
    }
    self.fetchTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .fetchTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.sizeBytes, forKey: .sizeBytes)
    try container.encode(self.hashes, forKey: .hashes)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.owner, forKey: .owner)
    try container.encodeIfPresent(self.fetchTime, forKey: .fetchTime)
    try container.encode(self.annotations, forKey: .annotations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.File"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
