// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of a single image manifest within a multi-arch image.
public struct ImageManifest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The CPU architecture of the image.
  /// Values are provided by the Docker client and are not validated by Artifact
  /// Registry. Example values include "amd64", "arm64", "ppc64le", "s390x",
  /// "riscv64", "mips64le", etc.
  public var architecture: Swift.String = Swift.String()

  /// Optional. The operating system of the image.
  /// Values are provided by the Docker client and are not validated by Artifact
  /// Registry. Example values include "linux", "windows", "darwin", "aix", etc.
  public var os: Swift.String = Swift.String()

  /// Optional. The manifest digest, in the format "sha256:<sha256_hex_digest>".
  public var digest: Swift.String = Swift.String()

  /// Optional. The media type of the manifest, e.g.,
  /// "application/vnd.docker.distribution.manifest.v2+json"
  public var mediaType: Swift.String = Swift.String()

  /// Optional. The OS version of the image, for example on Windows
  /// `10.0.14393.1066`.
  public var osVersion: Swift.String = Swift.String()

  /// Optional. The required OS features for the image, for example on Windows
  /// `win32k`.
  public var osFeatures: [Swift.String] = []

  /// Optional. The variant of the CPU in the image, for example `v7` to specify
  /// ARMv7 when architecture is `arm`.
  public var variant: Swift.String = Swift.String()

  /// Initialize a new instance of `ImageManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageManifest().with { $0.architecture = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ImageManifest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
