// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Error information explaining why a package was not imported.
public struct ImportYumArtifactsErrorInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The detailed error status.
  public var error: GoogleRpc.Status? = nil

  /// The source that was not imported.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `ImportYumArtifactsErrorInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportYumArtifactsErrorInfo().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsSource = "gcsSource"
    case error = "error"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsSource = try container.decodeIfPresent(
      ImportYumArtifactsGcsSource?.self, forKey: .gcsSource)
    {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.error, forKey: .error)

    if let choice = self.source {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      }
    }
  }

  /// The source that was not imported.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Google Cloud Storage location requested.
    indirect case gcsSource(ImportYumArtifactsGcsSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ImportYumArtifactsErrorInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
