// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request to list packages.
public struct ListPackagesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the parent resource whose packages will be listed.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of packages to return. Maximum page size is 1,000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The next_page_token value returned from a previous list request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. An expression for filtering the results of the request. Filter
  /// rules are case insensitive. The fields eligible for filtering are:
  ///
  ///   * `name`
  ///   * `annotations`
  ///
  /// Examples of using a filter:
  ///
  ///  To filter the results of your request to packages with the name
  ///  `my-package` in project `my-project` in the `us-central` region, in
  ///  repository `my-repo`, append the following filter expression to your
  ///  request:
  ///
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package"`
  ///
  ///  You can also use wildcards to match any number of characters before or
  ///  after the value:
  ///
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-*"`
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/*package"`
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/*pack*"`
  ///
  ///  To filter the results of your request to packages with the annotation
  ///  key-value pair [`external_link`: `external_link_value`], append the
  ///  following filter expression to your request":
  ///
  ///   * `"annotations.external_link:external_link_value"`
  ///
  ///  To filter the results just for a specific annotation key `external_link`,
  ///  append the following filter expression to your request:
  ///
  ///   * `"annotations.external_link"`
  ///
  ///  If the annotation key or value contains special characters, you can escape
  ///  them by surrounding the value with backticks. For example, to filter the
  ///  results of your request to packages with the annotation key-value pair
  ///  [`external.link`:`https://example.com/my-package`], append the following
  ///  filter expression to your request:
  ///
  ///   * `` "annotations.`external.link`:`https://example.com/my-package`" ``
  ///
  ///  You can also filter with annotations with a wildcard to
  ///  match any number of characters before or after the value:
  ///
  ///   * `` "annotations.*_link:`*example.com*`" ``
  public var filter: Swift.String = Swift.String()

  /// Optional. The field to order the results by.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListPackagesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPackagesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ListPackagesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
