// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MavenArtifact represents a maven artifact.
public struct MavenArtifact: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. registry_location, project_id, repository_name and maven_artifact
  /// forms a unique artifact For example,
  /// "projects/test-project/locations/us-west4/repositories/test-repo/mavenArtifacts/
  /// com.google.guava:guava:31.0-jre",
  /// where "us-west4" is the registry_location, "test-project" is the
  /// project_id, "test-repo" is the repository_name and
  /// "com.google.guava:guava:31.0-jre"
  /// is the maven artifact.
  public var name: Swift.String = Swift.String()

  /// Required. URL to access the pom file of the artifact.
  /// Example:
  /// us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.pom
  public var pomUri: Swift.String = Swift.String()

  /// Group ID for the artifact.
  /// Example:
  /// com.google.guava
  public var groupId: Swift.String = Swift.String()

  /// Artifact ID for the artifact.
  public var artifactId: Swift.String = Swift.String()

  /// Version of this artifact.
  public var version: Swift.String = Swift.String()

  /// Output only. Time the artifact was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time the artifact was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MavenArtifact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MavenArtifact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let pomUri = CodingKeys(stringValue: "pomUri")
    static let groupId = CodingKeys(stringValue: "groupId")
    static let artifactId = CodingKeys(stringValue: "artifactId")
    static let version = CodingKeys(stringValue: "version")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "pomUri",
      "groupId",
      "artifactId",
      "version",
      "createTime",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pomUri) {
      self.pomUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupId) {
      self.groupId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .artifactId) {
      self.artifactId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.pomUri, forKey: .pomUri)
    try container.encode(self.groupId, forKey: .groupId)
    try container.encode(self.artifactId, forKey: .artifactId)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.MavenArtifact"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
