// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// NpmPackage represents an npm artifact.
public struct NpmPackage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. registry_location, project_id, repository_name and npm_package
  /// forms a unique package For example,
  /// "projects/test-project/locations/us-west4/repositories/test-repo/npmPackages/
  /// npm_test:1.0.0",
  /// where "us-west4" is the registry_location, "test-project" is the
  /// project_id, "test-repo" is the repository_name and
  /// npm_test:1.0.0" is the npm package.
  public var name: Swift.String = Swift.String()

  /// Package for the artifact.
  public var packageName: Swift.String = Swift.String()

  /// Version of this package.
  public var version: Swift.String = Swift.String()

  /// Tags attached to this package.
  public var tags: [Swift.String] = []

  /// Output only. Time the package was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time the package was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `NpmPackage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NpmPackage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.NpmPackage"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
