// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Packages are named collections of versions.
public struct Package: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the package, for example:
  /// `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1`.
  /// If the package ID part contains slashes, the slashes are escaped.
  public var name: Swift.String = Swift.String()

  /// The display name of the package.
  public var displayName: Swift.String = Swift.String()

  /// The time when the package was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// The time when the package was last updated. This includes publishing a new
  /// version of the package.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Client specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Package`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Package().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.Package"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
