// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The Artifact Registry settings that apply to a Project.
public struct ProjectSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the project's settings.
  ///
  /// Always of the form:
  /// projects/{project-id}/projectSettings
  ///
  /// In update request: never set
  /// In response: always set
  public var name: Swift.String = Swift.String()

  /// The redirection state of the legacy repositories in this project.
  public var legacyRedirectionState: ProjectSettings.RedirectionState =
    ProjectSettings.RedirectionState()

  /// The percentage of pull traffic to redirect from GCR to AR when using
  /// partial redirection.
  public var pullPercent: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `ProjectSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProjectSettings().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible redirection states for legacy repositories.
  public enum RedirectionState: Codable, Equatable, Sendable {
    /// No redirection status has been set.
    case unspecified
    /// Redirection is disabled.
    case redirectionFromGcrIoDisabled
    /// Redirection is enabled.
    case redirectionFromGcrIoEnabled
    /// Redirection is enabled, and has been finalized so cannot be reverted.
    @available(*, deprecated)
    case redirectionFromGcrIoFinalized
    /// Redirection is enabled and missing images are copied from GCR
    case redirectionFromGcrIoEnabledAndCopying
    /// Redirection is partially enabled and missing images are copied from GCR
    case redirectionFromGcrIoPartialAndCopying
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .redirectionFromGcrIoDisabled: return 1
      case .redirectionFromGcrIoEnabled: return 2
      case .redirectionFromGcrIoFinalized: return 3
      case .redirectionFromGcrIoEnabledAndCopying: return 5
      case .redirectionFromGcrIoPartialAndCopying: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REDIRECTION_STATE_UNSPECIFIED"
      case .redirectionFromGcrIoDisabled: return "REDIRECTION_FROM_GCR_IO_DISABLED"
      case .redirectionFromGcrIoEnabled: return "REDIRECTION_FROM_GCR_IO_ENABLED"
      case .redirectionFromGcrIoFinalized: return "REDIRECTION_FROM_GCR_IO_FINALIZED"
      case .redirectionFromGcrIoEnabledAndCopying:
        return "REDIRECTION_FROM_GCR_IO_ENABLED_AND_COPYING"
      case .redirectionFromGcrIoPartialAndCopying:
        return "REDIRECTION_FROM_GCR_IO_PARTIAL_AND_COPYING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RedirectionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REDIRECTION_STATE_UNSPECIFIED": self = .unspecified
      case "REDIRECTION_FROM_GCR_IO_DISABLED": self = .redirectionFromGcrIoDisabled
      case "REDIRECTION_FROM_GCR_IO_ENABLED": self = .redirectionFromGcrIoEnabled
      case "REDIRECTION_FROM_GCR_IO_FINALIZED": self = .redirectionFromGcrIoFinalized
      case "REDIRECTION_FROM_GCR_IO_ENABLED_AND_COPYING":
        self = .redirectionFromGcrIoEnabledAndCopying
      case "REDIRECTION_FROM_GCR_IO_PARTIAL_AND_COPYING":
        self = .redirectionFromGcrIoPartialAndCopying
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RedirectionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .redirectionFromGcrIoDisabled
      case 2: self = .redirectionFromGcrIoEnabled
      case 3: self = .redirectionFromGcrIoFinalized
      case 5: self = .redirectionFromGcrIoEnabledAndCopying
      case 6: self = .redirectionFromGcrIoPartialAndCopying
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .redirectionFromGcrIoDisabled: return try container.encode(1)
      case .redirectionFromGcrIoEnabled: return try container.encode(2)
      case .redirectionFromGcrIoFinalized: return try container.encode(3)
      case .redirectionFromGcrIoEnabledAndCopying: return try container.encode(5)
      case .redirectionFromGcrIoPartialAndCopying: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ProjectSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
