// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The body of a version resource. A version resource represents a
/// collection of components, such as files and other data. This may correspond
/// to a version in many package management schemes.
public struct Version: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the version, for example:
  /// `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/versions/art1`.
  /// If the package or version ID parts contain slashes, the slashes are
  /// escaped.
  public var name: Swift.String = Swift.String()

  /// Optional. Description of the version, as specified in its metadata.
  public var description: Swift.String = Swift.String()

  /// The time when the version was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// The time when the version was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. A list of related tags. Will contain up to 100 tags that
  /// reference this version.
  public var relatedTags: [Tag] = []

  /// Output only. Repository-specific Metadata stored against this version.
  /// The fields returned are defined by the underlying repository-specific
  /// resource. Currently, the resources could be:
  /// [DockerImage][google.devtools.artifactregistry.v1.DockerImage]
  /// [MavenArtifact][google.devtools.artifactregistry.v1.MavenArtifact]
  ///
  /// [google.devtools.artifactregistry.v1.DockerImage]: <doc:DockerImage>
  /// [google.devtools.artifactregistry.v1.MavenArtifact]: <doc:MavenArtifact>
  public var metadata: GoogleWKT.Struct? = nil

  /// Optional. Client specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Immutable reference for the version, calculated based on the
  /// version's content. Currently we only support dirsum_sha256 hash algorithm.
  /// Additional hash algorithms may be added in the future.
  public var fingerprints: [Hash] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Version`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Version().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let relatedTags = CodingKeys(stringValue: "relatedTags")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let fingerprints = CodingKeys(stringValue: "fingerprints")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "updateTime",
      "relatedTags",
      "metadata",
      "annotations",
      "fingerprints",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Tag].self, forKey: .relatedTags) {
      self.relatedTags = value
    }
    self.metadata = try container.decodeIfPresent(GoogleWKT.Struct.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent([Hash].self, forKey: .fingerprints) {
      self.fingerprints = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.relatedTags, forKey: .relatedTags)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.fingerprints, forKey: .fingerprints)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.Version"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
