// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A detailed representation of a Yum artifact.
public struct YumArtifact: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The Artifact Registry resource name of the artifact.
  public var name: Swift.String = Swift.String()

  /// Output only. The yum package name of the artifact.
  public var packageName: Swift.String = Swift.String()

  /// Output only. An artifact is a binary or source package.
  public var packageType: YumArtifact.PackageType = YumArtifact.PackageType()

  /// Output only. Operating system architecture of the artifact.
  public var architecture: Swift.String = Swift.String()

  /// Initialize a new instance of `YumArtifact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = YumArtifact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Package type is either binary or source.
  public enum PackageType: Codable, Equatable, Sendable {
    /// Package type is not specified.
    case unspecified
    /// Binary package (.rpm).
    case binary
    /// Source package (.srpm).
    case source
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .binary: return 1
      case .source: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PACKAGE_TYPE_UNSPECIFIED"
      case .binary: return "BINARY"
      case .source: return "SOURCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PackageType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PACKAGE_TYPE_UNSPECIFIED": self = .unspecified
      case "BINARY": self = .binary
      case "SOURCE": self = .source
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PackageType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .binary
      case 2: self = .source
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .binary: return try container.encode(1)
      case .source: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.YumArtifact"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
