// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for exporting an artifact to a destination.
public struct ExportArtifactRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The repository of the artifact to export.
  /// Format: projects/{project}/locations/{location}/repositories/{repository}
  public var repository: Swift.String = Swift.String()

  /// The artifact to be exported.
  public var sourceArtifact: OneOf_SourceArtifact? = nil

  /// The destination to export the artifact to.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `ExportArtifactRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportArtifactRequest().with { $0.sourceVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case sourceVersion = "sourceVersion"
    case sourceTag = "sourceTag"
    case gcsPath = "gcsPath"
    case repository = "repository"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.repository = try container.decode(Swift.String.self, forKey: .repository)

    var sourceArtifact: OneOf_SourceArtifact? = nil
    let sourceArtifactCheckAndSet = {
      if sourceArtifact != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceArtifact'"))
      }
      sourceArtifact = $0
    }
    if let sourceVersion = try container.decodeIfPresent(Swift.String.self, forKey: .sourceVersion)
    {
      try sourceArtifactCheckAndSet(.sourceVersion(sourceVersion))
    }
    if let sourceTag = try container.decodeIfPresent(Swift.String.self, forKey: .sourceTag) {
      try sourceArtifactCheckAndSet(.sourceTag(sourceTag))
    }
    self.sourceArtifact = sourceArtifact

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsPath = try container.decodeIfPresent(Swift.String.self, forKey: .gcsPath) {
      try destinationCheckAndSet(.gcsPath(gcsPath))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.repository, forKey: .repository)

    if let choice = self.sourceArtifact {
      switch choice {
      case .sourceVersion(let value):
        try container.encode(value, forKey: .sourceVersion)
      case .sourceTag(let value):
        try container.encode(value, forKey: .sourceTag)
      }
    }

    if let choice = self.destination {
      switch choice {
      case .gcsPath(let value):
        try container.encode(value, forKey: .gcsPath)
      }
    }
  }

  /// The artifact to be exported.
  public enum OneOf_SourceArtifact: Codable, Equatable, Sendable {
    /// The artifact version to export.
    /// Format:
    /// projects/{project}/locations/{location}/repositories/{repository}/packages/{package}/versions/{version}
    case sourceVersion(Swift.String)
    /// The artifact tag to export.
    /// Format:projects/{project}/locations/{location}/repositories/{repository}/packages/{package}/tags/{tag}
    case sourceTag(Swift.String)
  }

  /// The destination to export the artifact to.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// The Cloud Storage path to export the artifact to. Should start with the
    /// bucket name, and optionally have a directory path. Examples:
    /// `dst_bucket`, `dst_bucket/sub_dir`.
    /// Existing objects with the same path will be overwritten.
    case gcsPath(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ExportArtifactRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
