// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Files store content that is potentially associated with Packages or Versions.
public struct File: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the file, for example:
  /// `projects/p1/locations/us-central1/repositories/repo1/files/a%2Fb%2Fc.txt`.
  /// If the file ID part contains slashes, they are escaped.
  public var name: Swift.String = Swift.String()

  /// The size of the File in bytes.
  public var sizeBytes: Swift.Int64 = Swift.Int64()

  /// The hashes of the file content.
  public var hashes: [Hash] = []

  /// Output only. The time when the File was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the File was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The name of the Package or Version that owns this file, if any.
  public var owner: Swift.String = Swift.String()

  /// Output only. The time when the last attempt to refresh the file's data was
  /// made. Only set when the repository is remote.
  public var fetchTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Client specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `File`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = File().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.File"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
