// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request to list tags.
public struct ListTagsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the parent package whose tags will be listed.
  /// For example:
  /// `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1`.
  public var parent: Swift.String = Swift.String()

  /// An expression for filtering the results of the request. Filter rules are
  /// case insensitive. The fields eligible for filtering are:
  ///
  ///   * `name`
  ///   * `version`
  ///
  ///  Examples of using a filter:
  ///
  ///  To filter the results of your request to tags with the name `my-tag` in
  ///  package `my-package` in repository `my-repo` in project "`y-project` in
  ///  the us-central region, append the following filter expression to your
  ///  request:
  ///
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/my-tag"`
  ///
  ///  You can also use wildcards to match any number of characters before or
  ///  after the value:
  ///
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/my*"`
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/*tag"`
  ///   * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/*tag*"`
  ///
  ///  To filter the results of your request to tags applied to the version
  ///  `1.0` in package `my-package`, append the following filter expression to
  ///  your request:
  ///
  ///   * `version="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/versions/1.0"`
  public var filter: Swift.String = Swift.String()

  /// The maximum number of tags to return. Maximum page size is 1,000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The next_page_token value returned from a previous list request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListTagsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTagsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.ListTagsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
