// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// MavenArtifact represents a maven artifact.
public struct MavenArtifact: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. registry_location, project_id, repository_name and maven_artifact
  /// forms a unique artifact For example,
  /// "projects/test-project/locations/us-west4/repositories/test-repo/mavenArtifacts/
  /// com.google.guava:guava:31.0-jre",
  /// where "us-west4" is the registry_location, "test-project" is the
  /// project_id, "test-repo" is the repository_name and
  /// "com.google.guava:guava:31.0-jre"
  /// is the maven artifact.
  public var name: Swift.String = Swift.String()

  /// Required. URL to access the pom file of the artifact.
  /// Example:
  /// us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.pom
  public var pomUri: Swift.String = Swift.String()

  /// Group ID for the artifact.
  /// Example:
  /// com.google.guava
  public var groupId: Swift.String = Swift.String()

  /// Artifact ID for the artifact.
  public var artifactId: Swift.String = Swift.String()

  /// Version of this artifact.
  public var version: Swift.String = Swift.String()

  /// Output only. Time the artifact was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time the artifact was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `MavenArtifact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MavenArtifact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.MavenArtifact"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
