// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The Artifact Registry VPC SC config that apply to a Project.
public struct VPCSCConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the project's VPC SC Config.
  ///
  /// Always of the form:
  /// projects/{projectID}/locations/{location}/vpcscConfig
  ///
  /// In update request: never set
  /// In response: always set
  public var name: Swift.String = Swift.String()

  /// The project per location VPC SC policy that defines the VPC SC behavior for
  /// the Remote Repository (Allow/Deny).
  public var vpcscPolicy: VPCSCConfig.VPCSCPolicy = VPCSCConfig.VPCSCPolicy()

  /// Initialize a new instance of `VPCSCConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VPCSCConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// VPCSCPolicy is the VPC SC policy for project and location.
  public enum VPCSCPolicy: Codable, Equatable, Sendable {
    /// VPCSC_POLICY_UNSPECIFIED - the VPS SC policy is not defined.
    /// When VPS SC policy is not defined - the Service will use the default
    /// behavior (VPCSC_DENY).
    case unspecified
    /// VPCSC_DENY - repository will block the requests to the Upstreams for the
    /// Remote Repositories if the resource is in the perimeter.
    case deny
    /// VPCSC_ALLOW - repository will allow the requests to the Upstreams for the
    /// Remote Repositories if the resource is in the perimeter.
    case allow
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .deny: return 1
      case .allow: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VPCSC_POLICY_UNSPECIFIED"
      case .deny: return "DENY"
      case .allow: return "ALLOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VPCSCPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VPCSC_POLICY_UNSPECIFIED": self = .unspecified
      case "DENY": self = .deny
      case "ALLOW": self = .allow
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VPCSCPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .deny
      case 2: self = .allow
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .deny: return try container.encode(1)
      case .allow: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.artifactregistry.v1.VPCSCConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
